model:
  name: 'CLIP:ViT-B/32'
  temperature: 100
  lora:
    apply: true
    r: 4
    alpha: 8
    dropout_rate: 0.25
    params: ['q', 'k', 'v', 'o']
    encoder: 'both' # both,
    position: 'all'
  residual_adapter:
    apply: false
    target: 'both' # 'vision', 'text', 'both'
    alpha: 0.5
    bottleneck_reduction: 4
  calibrate: false
  load_weights: false # false or path to file
  train_temperature: false
train:
  batch_size: 64
  epochs: 100
  learning_rate: 0.0005
  cooling:
    apply: linear # 'step', 'linear' or false
    final_temp: 34.723667
    iterations: 40000
dataset:
  name: 'nwpu'
  root: 'D:\\datasets\\nwpu\\'
  train_annotation: 'train.json'
  val_annotation: 'val.json'
output_dir: 'D:\\checkpoints\\test\\'
log_interval: 100